version: '3.8'
services:
  namenode:
    build: ./namenode
    ports:
      - "8000:80"
  datanode1:
    build: ./datanode
    ports:
      - "8001:8000"
  datanode2:
    build: ./datanode
    ports:
      - "8002:8000"
  datanode3:
    build: ./datanode
    ports:
      - "8003:8000"
